name: Auto Merge to Main

on:
  push:
    branches:
      - backend

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Merge brain-backend into main
        run: git merge --no-ff ${{ github.event.before }} --no-edit

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Push changes to main
        if: success()
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git push

      - name: Verify merge
        run: git log --oneline -5
